spring.application.name=ApiGateway-4SA11
server.port=8093


#eureka
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#debug
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG


spring.cloud.gateway.routes[0].id=vol-route
spring.cloud.gateway.routes[0].uri=lb://Vol  # Case-sensitive match
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/flights/**